services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-latest}
        GOOS: ${GOOS:-linux}
        GOARCH: ${GOARCH:-amd64}
    image: golang-todo-app:${APP_VERSION:-latest}
    container_name: golang-todo-app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      SERVER_BIND_ADDRESS: "${SERVER_BIND_ADDRESS}"
      SERVER_PORT: "${SERVER_PORT}"
      LOG_LEVEL: "${LOG_LEVEL}"
      CORS_ORIGIN: "${CORS_ORIGIN}"
      PG_POOL_MAX_CONN: "${POSTGRES_POOL_MAX_CONN}"
      PG_POOL_MIN_CONN: "${POSTGRES_POOL_MIN_CONN}"
    depends_on:
      - db
    networks:
      - todo-network

  db:
    image: postgres:${POSTGRES_VERSION:-latest}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge
