// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/google/uuid"
	"github.com/henryhall897/golang-todo-app/internal/users"
	"sync"
)

// Ensure, that UserRepositoryMock does implement users.UserRepository.
// If this is not the case, regenerate this file with moq.
var _ users.UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of users.UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked users.UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			CreateUserFunc: func(ctx context.Context, newUserParams users.CreateUserParams) (users.User, error) {
//				panic("mock out the CreateUser method")
//			},
//			DeleteUserFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the DeleteUser method")
//			},
//			GetUserByEmailFunc: func(ctx context.Context, email string) (users.User, error) {
//				panic("mock out the GetUserByEmail method")
//			},
//			GetUserByIDFunc: func(ctx context.Context, id uuid.UUID) (users.User, error) {
//				panic("mock out the GetUserByID method")
//			},
//			ListUsersFunc: func(ctx context.Context, params users.ListUsersParams) ([]users.User, error) {
//				panic("mock out the ListUsers method")
//			},
//			UpdateUserFunc: func(ctx context.Context, updateUserparams users.UpdateUserParams) (users.User, error) {
//				panic("mock out the UpdateUser method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires users.UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, newUserParams users.CreateUserParams) (users.User, error)

	// DeleteUserFunc mocks the DeleteUser method.
	DeleteUserFunc func(ctx context.Context, id uuid.UUID) error

	// GetUserByEmailFunc mocks the GetUserByEmail method.
	GetUserByEmailFunc func(ctx context.Context, email string) (users.User, error)

	// GetUserByIDFunc mocks the GetUserByID method.
	GetUserByIDFunc func(ctx context.Context, id uuid.UUID) (users.User, error)

	// ListUsersFunc mocks the ListUsers method.
	ListUsersFunc func(ctx context.Context, params users.ListUsersParams) ([]users.User, error)

	// UpdateUserFunc mocks the UpdateUser method.
	UpdateUserFunc func(ctx context.Context, updateUserparams users.UpdateUserParams) (users.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// NewUserParams is the newUserParams argument value.
			NewUserParams users.CreateUserParams
		}
		// DeleteUser holds details about calls to the DeleteUser method.
		DeleteUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetUserByEmail holds details about calls to the GetUserByEmail method.
		GetUserByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// GetUserByID holds details about calls to the GetUserByID method.
		GetUserByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// ListUsers holds details about calls to the ListUsers method.
		ListUsers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params users.ListUsersParams
		}
		// UpdateUser holds details about calls to the UpdateUser method.
		UpdateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UpdateUserparams is the updateUserparams argument value.
			UpdateUserparams users.UpdateUserParams
		}
	}
	lockCreateUser     sync.RWMutex
	lockDeleteUser     sync.RWMutex
	lockGetUserByEmail sync.RWMutex
	lockGetUserByID    sync.RWMutex
	lockListUsers      sync.RWMutex
	lockUpdateUser     sync.RWMutex
}

// CreateUser calls CreateUserFunc.
func (mock *UserRepositoryMock) CreateUser(ctx context.Context, newUserParams users.CreateUserParams) (users.User, error) {
	if mock.CreateUserFunc == nil {
		panic("UserRepositoryMock.CreateUserFunc: method is nil but UserRepository.CreateUser was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		NewUserParams users.CreateUserParams
	}{
		Ctx:           ctx,
		NewUserParams: newUserParams,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(ctx, newUserParams)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedUserRepository.CreateUserCalls())
func (mock *UserRepositoryMock) CreateUserCalls() []struct {
	Ctx           context.Context
	NewUserParams users.CreateUserParams
} {
	var calls []struct {
		Ctx           context.Context
		NewUserParams users.CreateUserParams
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// DeleteUser calls DeleteUserFunc.
func (mock *UserRepositoryMock) DeleteUser(ctx context.Context, id uuid.UUID) error {
	if mock.DeleteUserFunc == nil {
		panic("UserRepositoryMock.DeleteUserFunc: method is nil but UserRepository.DeleteUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteUser.Lock()
	mock.calls.DeleteUser = append(mock.calls.DeleteUser, callInfo)
	mock.lockDeleteUser.Unlock()
	return mock.DeleteUserFunc(ctx, id)
}

// DeleteUserCalls gets all the calls that were made to DeleteUser.
// Check the length with:
//
//	len(mockedUserRepository.DeleteUserCalls())
func (mock *UserRepositoryMock) DeleteUserCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDeleteUser.RLock()
	calls = mock.calls.DeleteUser
	mock.lockDeleteUser.RUnlock()
	return calls
}

// GetUserByEmail calls GetUserByEmailFunc.
func (mock *UserRepositoryMock) GetUserByEmail(ctx context.Context, email string) (users.User, error) {
	if mock.GetUserByEmailFunc == nil {
		panic("UserRepositoryMock.GetUserByEmailFunc: method is nil but UserRepository.GetUserByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetUserByEmail.Lock()
	mock.calls.GetUserByEmail = append(mock.calls.GetUserByEmail, callInfo)
	mock.lockGetUserByEmail.Unlock()
	return mock.GetUserByEmailFunc(ctx, email)
}

// GetUserByEmailCalls gets all the calls that were made to GetUserByEmail.
// Check the length with:
//
//	len(mockedUserRepository.GetUserByEmailCalls())
func (mock *UserRepositoryMock) GetUserByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockGetUserByEmail.RLock()
	calls = mock.calls.GetUserByEmail
	mock.lockGetUserByEmail.RUnlock()
	return calls
}

// GetUserByID calls GetUserByIDFunc.
func (mock *UserRepositoryMock) GetUserByID(ctx context.Context, id uuid.UUID) (users.User, error) {
	if mock.GetUserByIDFunc == nil {
		panic("UserRepositoryMock.GetUserByIDFunc: method is nil but UserRepository.GetUserByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetUserByID.Lock()
	mock.calls.GetUserByID = append(mock.calls.GetUserByID, callInfo)
	mock.lockGetUserByID.Unlock()
	return mock.GetUserByIDFunc(ctx, id)
}

// GetUserByIDCalls gets all the calls that were made to GetUserByID.
// Check the length with:
//
//	len(mockedUserRepository.GetUserByIDCalls())
func (mock *UserRepositoryMock) GetUserByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetUserByID.RLock()
	calls = mock.calls.GetUserByID
	mock.lockGetUserByID.RUnlock()
	return calls
}

// ListUsers calls ListUsersFunc.
func (mock *UserRepositoryMock) ListUsers(ctx context.Context, params users.ListUsersParams) ([]users.User, error) {
	if mock.ListUsersFunc == nil {
		panic("UserRepositoryMock.ListUsersFunc: method is nil but UserRepository.ListUsers was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params users.ListUsersParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockListUsers.Lock()
	mock.calls.ListUsers = append(mock.calls.ListUsers, callInfo)
	mock.lockListUsers.Unlock()
	return mock.ListUsersFunc(ctx, params)
}

// ListUsersCalls gets all the calls that were made to ListUsers.
// Check the length with:
//
//	len(mockedUserRepository.ListUsersCalls())
func (mock *UserRepositoryMock) ListUsersCalls() []struct {
	Ctx    context.Context
	Params users.ListUsersParams
} {
	var calls []struct {
		Ctx    context.Context
		Params users.ListUsersParams
	}
	mock.lockListUsers.RLock()
	calls = mock.calls.ListUsers
	mock.lockListUsers.RUnlock()
	return calls
}

// UpdateUser calls UpdateUserFunc.
func (mock *UserRepositoryMock) UpdateUser(ctx context.Context, updateUserparams users.UpdateUserParams) (users.User, error) {
	if mock.UpdateUserFunc == nil {
		panic("UserRepositoryMock.UpdateUserFunc: method is nil but UserRepository.UpdateUser was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		UpdateUserparams users.UpdateUserParams
	}{
		Ctx:              ctx,
		UpdateUserparams: updateUserparams,
	}
	mock.lockUpdateUser.Lock()
	mock.calls.UpdateUser = append(mock.calls.UpdateUser, callInfo)
	mock.lockUpdateUser.Unlock()
	return mock.UpdateUserFunc(ctx, updateUserparams)
}

// UpdateUserCalls gets all the calls that were made to UpdateUser.
// Check the length with:
//
//	len(mockedUserRepository.UpdateUserCalls())
func (mock *UserRepositoryMock) UpdateUserCalls() []struct {
	Ctx              context.Context
	UpdateUserparams users.UpdateUserParams
} {
	var calls []struct {
		Ctx              context.Context
		UpdateUserparams users.UpdateUserParams
	}
	mock.lockUpdateUser.RLock()
	calls = mock.calls.UpdateUser
	mock.lockUpdateUser.RUnlock()
	return calls
}
