apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: golang-todo-app-ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`golang-todo.local`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: golang-todo-app-helm-chart
          port: 80


