apiVersion: v1
kind: Secret
metadata:
  name: golang-todo-secret
type: Opaque
data:
  DATABASE_URL: {{.Values.secrets.DATABASE_URL | b64enc}}
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc }}
  DOCKER_HUB_USERNAME: {{ .Values.secrets.DOCKER_HUB_USERNAME | b64enc }}
