replicaCount: 1

image:
  repository: docker_hub_username/app_name
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

secrets:
  POSTGRES_USER: "postgres_user"
  POSTGRES_PASSWORD: "postgres_password"
  DATABASE_URL: "database_url"
  DOCKER_HUB_USERNAME: "docker_hub_username"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi