package todolist

import (
	"fmt"
	"golang-todo-app/internal/todo_list/gen"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// toAppTodoList transforms a database (SQLC-generated) gen.TodoList to an application-level TodoList.
func toAppTodoList(todo gen.TodoList) (TodoList, error) {
	if !todo.ID.Valid {
		return TodoList{}, fmt.Errorf("invalid todo list id")
	}
	if !todo.UserID.Valid {
		return TodoList{}, fmt.Errorf("invalid user id")
	}

	// Convert pgtype.UUID to uuid.UUID
	id, err := uuid.FromBytes(todo.ID.Bytes[:])
	if err != nil {
		return TodoList{}, fmt.Errorf("failed to parse todo list id: %w", err)
	}

	userID, err := uuid.FromBytes(todo.UserID.Bytes[:])
	if err != nil {
		return TodoList{}, fmt.Errorf("failed to parse user id: %w", err)
	}

	// Transform the TodoList structure
	return TodoList{
		ID:          id,
		UserID:      userID,
		Name:        todo.Name,
		Description: todo.Description.String,
		CreatedAt:   todo.CreatedAt.Time,
		UpdatedAt:   todo.UpdatedAt.Time,
	}, nil
}

// toDBTodoList converts Go standard types into a database-compatible TodoList with pgtype fields.
func toDBTodoList(id uuid.UUID, userID uuid.UUID, name string, description *string) (gen.TodoList, error) {
	// Convert UUIDs
	dbID := pgtype.UUID{
		Bytes: id,
		Valid: id != uuid.Nil, // ID can be invalid (Nil) for new records
	}
	dbUserID := pgtype.UUID{
		Bytes: userID,
		Valid: userID != uuid.Nil,
	}

	// Validate userID
	if !dbUserID.Valid {
		return gen.TodoList{}, fmt.Errorf("invalid UUID for user_id")
	}

	// Convert description to pgtype.Text
	var dbDescription pgtype.Text
	if description != nil {
		dbDescription = pgtype.Text{
			String: *description,
			Valid:  true,
		}
	} else {
		dbDescription = pgtype.Text{
			Valid: false,
		}
	}

	// Return the transformed TodoList
	return gen.TodoList{
		ID:          dbID, // May be Nil for new records
		UserID:      dbUserID,
		Name:        name,
		Description: dbDescription,
	}, nil
}

// toDBUUID converts a uuid.UUID to a database-compatible pgtype.UUID.
func toDBUUID(id uuid.UUID) (pgtype.UUID, error) {
	if id == uuid.Nil {
		return pgtype.UUID{}, fmt.Errorf("invalid UUID: UUID is nil")
	}
	return pgtype.UUID{
		Bytes: id,
		Valid: true,
	}, nil
}

// toDBTodoListForCreate allows nil ID since it's generated by the database.
func toDBTodoListForCreate(userID uuid.UUID, name string, description *string) (gen.TodoList, error) {
	return toDBTodoList(uuid.Nil, userID, name, description)
}

// toDBTodoListForUpdate requires a valid ID.
func toDBTodoListForUpdate(id uuid.UUID, userID uuid.UUID, name string, description *string) (gen.TodoList, error) {
	if id == uuid.Nil {
		return gen.TodoList{}, fmt.Errorf("invalid UUID for id")
	}
	return toDBTodoList(id, userID, name, description)
}
