name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug SSH Connection
        run: |
          ssh -v deployuser@192.168.1.231 "echo 'SSH connection successful!'"
          
      - name: Set up SSH Key
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/id_ed25519"
          chmod 600 "$HOME/.ssh/id_ed25519"
          ssh-keyscan -H 192.168.1.231 >> "$HOME/.ssh/known_hosts"
          chmod 644 "$HOME/.ssh/known_hosts"
          eval "$(ssh-agent -s)"
          ssh-add "$HOME/.ssh/id_ed25519"



      - name: Deploy with Helm
        run: |
          ssh deployuser@192.168.1.231 << 'EOF'
            cd /home/deployuser/todo 
            git pull origin master  
            helm upgrade --install golang-todo-app ./helm-chart/  
          EOF
