name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          if ! ssh-keyscan -H cluster1 >> ~/.ssh/known_hosts; then
          echo "Failed to add host to known_hosts"
          exit 1
          fi
        shell: bash

      - name: Deploy with Helm
        run: |
          ssh deployuser@cluster1 << 'EOF'
            cd /home/deployuser/todo 
            git pull origin master  
            helm upgrade --install golang-todo-app ./helm-chart/  
          EOF
